package server

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/google/uuid"
	"io"
	"net/http"
	"sync"
	"time"

	"github.com/loppo-llc/kojo/internal/agent"
	"github.com/loppo-llc/kojo/internal/store"
)

// docs/multi-device-storage.md §3.7 — agent-sync finalize.
//
// The agent-sync push (`POST /api/v1/peers/agent-sync`) lands
// the source's row state on target BEFORE the blob pull and the
// complete commit. If anything between (pull or complete) fails,
// the switch aborts and target's runtime state should NOT
// activate the agent — otherwise target ends up with a valid
// token + lock-guard entry for an agent whose blobs never
// arrived, which would let an unsuspecting Bearer holder write
// to half-migrated state.
//
// The orchestrator dispatches this finalize POST only after a
// successful complete. The handler:
//
//   - consumes the raw $KOJO_AGENT_TOKEN that agent-sync
//     stashed in pendingAgentTokens and adopts it via the local
//     TokenStore (so $KOJO_AGENT_TOKEN injection on the next
//     PTY spawn authenticates),
//   - signals the wired-in onAgentSyncFinalized hook (cmd/kojo
//     hooks AgentLockGuard.AddAgent here).
//
// Route: POST /api/v1/peers/agent-sync/finalize
// Auth: RolePeer (signer.PeerID must equal source_device_id) or
// RoleOwner. Same trust model as agent-sync itself.
//
// Body:
//
//	{ "source_device_id": "...", "agent_id": "..." }
//
// Idempotent: a second finalize for the same agent_id is a no-op
// because the pending token is already consumed.

type peerAgentSyncFinalizeRequest struct {
	SourceDeviceID string `json:"source_device_id"`
	AgentID        string `json:"agent_id"`
	// OpID matches the op_id stamped on the original
	// /peers/agent-sync request. Required for the two-phase
	// protocol; a finalize without a matching pending entry
	// fails 404 not_found rather than activating runtime state
	// blindly.
	OpID string `json:"op_id"`
	// TailMessage carries the assistant Message generated by source's
	// claude AFTER the kojo-switch-device tool_use returned but
	// BEFORE the chat goroutine exited. Optional: the orchestrator
	// includes it only on the self-call defer-finalize path where
	// the source-release guard would otherwise drop this turn.
	//
	// Handler ordering (see handlePeerAgentSyncFinalize):
	//   1. AcceptIncomingHandoff (atomic holder/token/proxy)
	//   2. onAgentSyncFinalized hook
	//   3. applyFinalizeTailMessage — UPSERTs the row by id under
	//      a FencingPredicate keyed on the post-hook lock token,
	//      so a force-reclaim race aborts the apply with
	//      errTailLockNotSelf (caller 503s, source retries).
	//   4. activate the receipt only after the tail is durable
	//   5. admit the arrival either to the initiating Slack/WebUI
	//      thread or, for legacy/main turns, to main WebUI
	//   6. commitPendingAgentSync
	//
	// Nil/empty on non-self-call paths and on self-call paths where
	// the source turn never emitted a done event within the wait
	// budget — the finalize still proceeds; target's arrival just
	// lacks the tail (degraded but functional).
	TailMessage *store.MessageRecord `json:"tail_message,omitempty"`
	// Continuation routes the arrival system turn back through the Hub-owned
	// response adapter that initiated the switch. Nil preserves the legacy main
	// WebUI arrival chat.
	Continuation *handoffContinuation `json:"continuation,omitempty"`
}

type handoffContinuation struct {
	GoalHandoffID string `json:"goal_handoff_id,omitempty"`
	SessionKey    string `json:"session_key"`
	OriginPeerID  string `json:"origin_peer_id"`
	Capability    string `json:"capability"`
}

type peerAgentSyncFinalizeResponse struct {
	AgentID string `json:"agent_id"`
}

type pendingFinalizeLock struct {
	mu   sync.Mutex
	refs int
}

func (s *Server) lockPendingFinalize(key pendingSyncKey) func() {
	s.pendingFinalizeMu.Lock()
	if s.pendingFinalizeLocks == nil {
		s.pendingFinalizeLocks = make(map[pendingSyncKey]*pendingFinalizeLock)
	}
	entry := s.pendingFinalizeLocks[key]
	if entry == nil {
		entry = &pendingFinalizeLock{}
		s.pendingFinalizeLocks[key] = entry
	}
	entry.refs++
	s.pendingFinalizeMu.Unlock()

	entry.mu.Lock()
	return func() {
		entry.mu.Unlock()
		s.pendingFinalizeMu.Lock()
		entry.refs--
		if entry.refs == 0 {
			delete(s.pendingFinalizeLocks, key)
		}
		s.pendingFinalizeMu.Unlock()
	}
}

func (s *Server) handlePeerAgentSyncFinalize(w http.ResponseWriter, r *http.Request) {
	p, ok := requirePeerOrOwner(w, r)
	if !ok {
		return
	}
	// Body cap raised to 16 MiB to admit an optional TailMessage —
	// an assistant turn with long Markdown, multi-tool ToolUses
	// JSON, and tool outputs can easily exceed the legacy 4 KiB.
	// The bound stays well under peerAgentSyncMaxBody so a runaway
	// tail can't exhaust the receiver.
	body, err := io.ReadAll(http.MaxBytesReader(w, r.Body, 16<<20))
	if err != nil {
		writeError(w, http.StatusBadRequest, "bad_request",
			"read body: "+err.Error())
		return
	}
	var req peerAgentSyncFinalizeRequest
	dec := json.NewDecoder(bytes.NewReader(body))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "bad_request",
			"invalid json: "+err.Error())
		return
	}
	if req.SourceDeviceID == "" || req.AgentID == "" || req.OpID == "" {
		writeError(w, http.StatusBadRequest, "bad_request",
			"source_device_id, agent_id, and op_id required")
		return
	}
	if c := req.Continuation; c != nil && c.GoalHandoffID != "" {
		if _, err := uuid.Parse(c.GoalHandoffID); err != nil || c.GoalHandoffID != req.OpID || c.Capability != "" || c.OriginPeerID == "" {
			writeError(w, 400, "bad_request", "invalid goal handoff continuation")
			return
		}
	}
	if req.Continuation != nil && req.Continuation.GoalHandoffID == "" && (req.Continuation.SessionKey == "" || req.Continuation.OriginPeerID == "" || req.Continuation.Capability == "") {
		writeError(w, http.StatusBadRequest, "bad_request",
			"continuation.session_key, continuation.origin_peer_id, and continuation.capability required")
		return
	}
	if !verifySignerIsSource(p, req.SourceDeviceID) {
		writeError(w, http.StatusForbidden, "forbidden",
			"signer peer device_id does not match source_device_id")
		return
	}
	allowedProxy, err := s.resolveAllowedProxyPeer(r.Context(), req)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			writeError(w, http.StatusForbidden, "forbidden",
				"continuation.origin_peer_id is not a paired peer")
			return
		}
		s.logger.Error("peer agent-sync finalize: origin peer validation failed",
			"agent", req.AgentID, "origin_peer", req.Continuation.OriginPeerID, "err", err)
		writeError(w, http.StatusInternalServerError, "internal",
			"validate continuation origin peer: "+err.Error())
		return
	}
	// Serialize the entire consume → arrival decision → commit sequence for
	// this agent, including force-reclaim. Only one retry may decide between origin
	// admission and legacy fallback; later retries observe the committed 404.
	unlockFinalize := s.lockPendingFinalize(pendingSyncKey{AgentID: req.AgentID})
	defer unlockFinalize()

	entry, ok, err := s.consumePendingAgentSync(r.Context(), req.AgentID, req.OpID)
	if err != nil {
		s.logger.Error("peer agent-sync finalize: pending lookup failed",
			"agent", req.AgentID, "op_id", req.OpID, "err", err)
		writeError(w, http.StatusInternalServerError, "internal",
			"pending lookup: "+err.Error())
		return
	}
	if !ok {
		// No matching sync stash. Two cases:
		//   - the orchestrator never sent the agent-sync for
		//     this op_id (forged or wrong-host finalize)
		//   - a prior finalize already committed and removed
		//     the entry (idempotent re-call)
		// Both are surfaced as 404; the orchestrator conservatively reports
		// failure because this alone cannot prove that runtime activation ran.
		writeError(w, http.StatusNotFound, "not_found",
			"no pending agent-sync for the given (agent_id, op_id); finalize already committed or sync never landed")
		return
	}
	if entry.SourceDeviceID != "" && entry.SourceDeviceID != req.SourceDeviceID {
		writeError(w, 403, "forbidden", "finalize source differs from phase-1 source")
		return
	}
	if s.peerID != nil && s.agents != nil && s.agents.Store() != nil {
		if !entry.IncomingFenced {
			writeError(w, 409, "legacy_handoff_pending", "pending operation predates ownership fencing; start a new handoff")
			return
		}
		accepted, err := s.agents.Store().AcceptIncomingHandoff(r.Context(), req.AgentID, req.OpID, req.SourceDeviceID, s.peerID.DeviceID, allowedProxy, store.NowMillis(), forceReclaimLeaseDuration.Milliseconds())
		if err != nil {
			if errors.Is(err, store.ErrStaleHandoff) || errors.Is(err, store.ErrNotFound) {
				writeError(w, 409, "stale_handoff", err.Error())
			} else {
				writeError(w, 503, "handoff_accept_failed", err.Error())
			}
			return
		}
		if accepted.Phase == "done" {
			if err := s.commitPendingAgentSync(r.Context(), req.AgentID, req.OpID); err != nil {
				writeError(w, 500, "internal", err.Error())
				return
			}
			writeJSONResponse(w, http.StatusOK, peerAgentSyncFinalizeResponse{AgentID: req.AgentID})
			return
		}
		// Startup deliberately evicts incomplete incoming snapshots. A retry
		// must reload only after validating its durable receipt, before the
		// activation hook registers schedulers or admits an arrival.
		if _, exists := s.agents.Get(req.AgentID); !exists {
			if err := s.agents.ReloadAgentFromStore(req.AgentID); err != nil {
				writeError(w, 503, "handoff_reload_failed", err.Error())
				return
			}
		}
	}
	tokenReissued := false
	if s.onAgentSyncFinalized != nil {
		reissued, err := s.onAgentSyncFinalized(r.Context(), req.AgentID, entry.RawToken, allowedProxy, req.OpID)
		tokenReissued = reissued
		if err != nil {
			// Lock-race surface: cmd/kojo's hook wraps a
			// post-AddAgent holder-mismatch with
			// store.ErrFencingMismatch so the source-side retry
			// loop (which keys on the "lock_not_self" substring)
			// picks it up. Without this translation the retry
			// loop sees a generic 500 and gives up after one
			// attempt — bug observed by codex review when the
			// lock hasn't yet propagated to target's local
			// agent_locks at the moment finalize lands.
			if errors.Is(err, store.ErrFencingMismatch) {
				s.logger.Warn("peer agent-sync finalize: hook lock_not_self; pending retained for retry",
					"agent", req.AgentID, "op_id", req.OpID, "err", err)
				writeError(w, http.StatusServiceUnavailable, "lock_not_self",
					"finalize hook: agent_locks holder mismatch; finalize aborted, orchestrator may retry")
				return
			}
			// Other hook failures (e.g. transient kv write error
			// on AdoptAgentTokenFromPeer) stay as 500 with the
			// pending entry retained. The source-side retry loop
			// only catches lock_not_self; non-matching errors
			// require operator intervention.
			s.logger.Error("peer agent-sync finalize: hook failed; pending entry retained for retry",
				"agent", req.AgentID, "op_id", req.OpID, "err", err)
			writeError(w, http.StatusInternalServerError, "internal",
				"finalize hook: "+err.Error())
			return
		}
	}
	// Apply the optional tail after the runtime hook but BEFORE activation:
	// activation opens local turn admission, and a turn admitted in that gap
	// would read history without the source's final message. AppendMessage
	// independently verifies the current local fencing token in its
	// transaction, and a lock_not_self here leaves the fence un-activated so
	// the orchestrator's retry re-runs the whole tail+activate sequence.
	if req.TailMessage != nil && s.agents != nil && s.agents.Store() != nil {
		if err := s.applyFinalizeTailMessage(r.Context(), req.AgentID, req.TailMessage); err != nil {
			if errors.Is(err, errTailLockNotSelf) {
				s.logger.Warn("peer agent-sync finalize: tail apply lock_not_self after hook; pending retained for retry",
					"agent", req.AgentID, "op_id", req.OpID)
				writeError(w, http.StatusServiceUnavailable, "lock_not_self",
					"tail apply: agent_locks.holder_peer is not the local peer; finalize aborted, orchestrator may retry")
				return
			}
			s.logger.Error("peer agent-sync finalize: tail message apply failed; pending retained",
				"agent", req.AgentID, "op_id", req.OpID, "err", err)
			writeError(w, http.StatusInternalServerError, "internal",
				"tail message apply: "+err.Error())
			return
		}
	}
	// Accept committed holder+proxy together. Only mark admission-ready once
	// the runtime hook and the tail apply succeeded, without a second
	// holder-only proxy rewrite.
	if entry.IncomingFenced {
		if err := s.agents.Store().ActivateIncomingHandoff(r.Context(), req.AgentID, req.OpID); err != nil {
			writeError(w, 409, "stale_handoff", err.Error())
			return
		}
	}

	// Build the arrival only AFTER the tail apply and activation. The external continuation
	// carries this exact prompt to the Hub; the legacy path below asks Manager
	// to build the same prompt for main WebUI delivery.
	sourceName := req.SourceDeviceID
	notes := agent.ArrivalNotes{
		TokenReissued: tokenReissued, DegradedFlushes: entry.DegradedFlushes, TransferSkips: entry.TransferSkips,
	}
	if s.agents != nil {
		if req.SourceDeviceID != "" && s.agents.Store() != nil {
			if rec, gerr := s.agents.Store().GetPeer(r.Context(), req.SourceDeviceID); gerr == nil && rec.Name != "" {
				sourceName = rec.Name
			}
		}
	}
	// Admit the arrival before consuming the pending finalize marker. This
	// preserves the legacy crash-safety property: once finalize commits, either
	// the response adapter owns an admitted in-process FIFO reservation or Manager
	// has registered the main-WebUI arrival. Callback retries are idempotent by
	// capability+op_id, and Manager deduplicates the fallback by op_id, so a kv
	// delete failure can safely retry the whole finalize.
	if s.agents != nil {
		if req.Continuation != nil && req.Continuation.GoalHandoffID != "" {
			if !entry.ArrivalHandled {
				if entry.ArrivalUncertain {
					writeError(w, 503, "goal_resume_uncertain", "Goal handoff resume delivery is uncertain; inspect destination state before explicitly resuming")
					return
				}
				binding, err := s.agents.AcceptGoalHandoff(req.AgentID, req.Continuation.SessionKey, req.OpID, req.SourceDeviceID, s.peerID.DeviceID)
				if err != nil {
					writeError(w, 409, "goal_changed", err.Error())
					return
				}
				origin := binding.OriginPeerID
				if origin == "" {
					origin = req.SourceDeviceID
				}
				if err := s.callGoalHandoffOrigin(r.Context(), origin, goalHandoffOriginRequest{Action: "check", OpID: req.OpID, AgentID: req.AgentID}); err != nil {
					writeError(w, 409, "goal_handoff_stopped", err.Error())
					return
				}
				// Persist the uncertain intent only after the side-effect-free
				// origin check, immediately before the resume side effect; a
				// failed check must stay retryable rather than 503 forever.
				entry.ArrivalUncertain = true
				if err := s.recordPendingAgentSync(r.Context(), req.AgentID, req.OpID, entry); err != nil {
					writeError(w, 500, "internal", err.Error())
					return
				}
				recovery := goalRecoveryRequest{AgentID: req.AgentID, SessionKey: binding.SessionKey, ThreadID: binding.State.ThreadID, Generation: binding.Generation, UserID: binding.UserID, RunID: binding.RunID, HolderID: s.peerID.DeviceID, HandoffID: req.OpID}
				// Main WebUI follows the agent; Slack retains the original Hub.
				if binding.SessionKey != "" && binding.OriginPeerID != "" && binding.OriginPeerID != s.peerID.DeviceID {
					err = s.requestGoalRecovery(r.Context(), binding.OriginPeerID, recovery)
				} else {
					err = s.resumeGoalSurface(r.Context(), recovery)
				}
				if err != nil {
					writeError(w, 503, "goal_resume_uncertain", err.Error())
					return
				}
				entry.ArrivalUncertain = false
				entry.ArrivalHandled = true
				if err := s.updatePendingAgentSyncAfterSideEffect(r.Context(), req.AgentID, req.OpID, entry); err != nil {
					writeError(w, 500, "internal", err.Error())
					return
				}
			}
		} else if req.Continuation == nil {
			s.agents.NotifyDeviceSwitchArrival(req.AgentID, sourceName, req.OpID, notes)
		} else if entry.ArrivalUncertain {
			writeError(w, http.StatusServiceUnavailable, "arrival_not_admitted",
				"a previous origin-conversation delivery was uncertain; fallback remains suppressed")
			return
		} else if entry.ArrivalHandled {
			// A prior finalize admitted the origin turn (or its definite-failure
			// fallback) but failed while committing the pending row. Do not replay
			// the arrival; continue directly to the idempotent commit below.
		} else {
			arrivalReq := handoffArrivalRequest{
				HolderDeviceID: s.peerID.DeviceID,
				AgentID:        req.AgentID, OpID: req.OpID,
				SessionKey: req.Continuation.SessionKey, SourceDeviceID: req.SourceDeviceID,
				Notes: notes, Capability: req.Continuation.Capability,
			}
			fallback := func() {
				s.agents.NotifyDeviceSwitchArrival(req.AgentID, sourceName, req.OpID, notes)
			}
			// Write intent BEFORE the external side effect. A target crash after
			// origin admission but before persisting the outcome must not replay
			// an invalid capability after the origin also restarts.
			entry.ArrivalUncertain = true
			if err := s.recordPendingAgentSync(r.Context(), req.AgentID, req.OpID, entry); err != nil {
				writeError(w, http.StatusInternalServerError, "internal",
					"persist arrival intent: "+err.Error())
				return
			}
			if err := s.dispatchHandoffArrivalContinuation(r.Context(), req.Continuation.OriginPeerID, arrivalReq, fallback); err != nil {
				// Only a delivery that may have reached the Hub keeps the durable
				// intent; a definite failure (holder changed, verify error, no send
				// began) must not poison every later finalize with 503.
				if !errors.Is(err, errHandoffArrivalUncertain) {
					entry.ArrivalUncertain = false
					// The definite failure may itself be the request context being
					// cancelled; the clear must still persist or every later
					// finalize keeps returning 503.
					clearCtx, clearCancel := context.WithTimeout(context.WithoutCancel(r.Context()), 5*time.Second)
					perr := s.updatePendingAgentSyncAfterSideEffect(clearCtx, req.AgentID, req.OpID, entry)
					clearCancel()
					if perr != nil {
						s.logger.Error("peer agent-sync finalize: clearing arrival intent failed; pending retained",
							"agent", req.AgentID, "op_id", req.OpID, "err", perr)
					}
				}
				s.logger.Warn("peer agent-sync finalize: arrival was not admitted; pending retained for retry",
					"agent", req.AgentID, "op_id", req.OpID, "err", err)
				writeError(w, http.StatusServiceUnavailable, "arrival_not_admitted", err.Error())
				return
			}
			entry.ArrivalUncertain = false
			entry.ArrivalHandled = true
			if err := s.updatePendingAgentSyncAfterSideEffect(r.Context(), req.AgentID, req.OpID, entry); err != nil {
				s.logger.Error("peer agent-sync finalize: arrival decision persistence failed; pending retained",
					"agent", req.AgentID, "op_id", req.OpID, "err", err)
				writeError(w, http.StatusInternalServerError, "internal",
					"persist arrival decision: "+err.Error())
				return
			}
		}
	}

	// Hook + admit gate + tail + arrival admission all succeeded — NOW remove
	// the pending entry so a subsequent retry surfaces as the 404
	// idempotent path. A kv delete failure still surfaces as 500:
	// leaving the sealed token in place while telling the
	// orchestrator the op completed would let a later boot consume
	// the same (agent_id, op_id) and replay every hook side
	// effect. All hook steps are idempotent on retry.
	if entry.IncomingFenced {
		if err := s.agents.Store().FinishIncomingHandoff(r.Context(), req.AgentID, req.OpID); err != nil {
			writeError(w, 409, "stale_handoff", err.Error())
			return
		}
	}
	if err := s.commitPendingAgentSync(r.Context(), req.AgentID, req.OpID); err != nil {
		s.logger.Error("peer agent-sync finalize: commit kv delete failed; surface 500 for retry",
			"agent", req.AgentID, "op_id", req.OpID, "err", err)
		writeError(w, http.StatusInternalServerError, "internal",
			"commit kv delete: "+err.Error())
		return
	}
	// Queue-and-forward: the runtime for this agent just activated
	// on this peer (finalize committed). When this peer is the hub,
	// messages queued during the switch can deliver locally right
	// now instead of waiting out the drain's backoff timer; on a
	// non-hub peer the queue table is empty and this is a no-op.
	s.kickHandoffQueueDrain()
	// The designated arrival owns one conversation; restore any other active
	// goals transferred with the same agent through their original surfaces.
	excludeGoalKey := ""
	if req.Continuation != nil {
		excludeGoalKey = req.Continuation.SessionKey
	}
	go s.recoverNativeGoals(req.AgentID, excludeGoalKey, false)
	writeJSONResponse(w, http.StatusOK,
		peerAgentSyncFinalizeResponse{AgentID: req.AgentID})
}

func (s *Server) resolveAllowedProxyPeer(ctx context.Context, req peerAgentSyncFinalizeRequest) (string, error) {
	if req.Continuation == nil || req.Continuation.OriginPeerID == "" ||
		req.Continuation.OriginPeerID == req.SourceDeviceID {
		return req.SourceDeviceID, nil
	}
	// A return migration may target the response-surface Hub itself. Our own
	// identity is trusted without a self-entry in peer_registry.
	if s != nil && s.peerID != nil && req.Continuation.OriginPeerID == s.peerID.DeviceID {
		return s.peerID.DeviceID, nil
	}
	// SourceDeviceID is bound to the authenticated signer above. A distinct
	// response-surface Hub is safe only when it is already in peer_registry;
	// otherwise a paired source could nominate an arbitrary third device for
	// agent_locks.allowed_proxy_peer.
	if s == nil || s.agents == nil || s.agents.Store() == nil {
		return "", errors.New("peer registry is unavailable")
	}
	if _, err := s.agents.Store().GetPeer(ctx, req.Continuation.OriginPeerID); err != nil {
		return "", err
	}
	return req.Continuation.OriginPeerID, nil
}

// errTailLockNotSelf signals that the tail apply could not proceed
// because target's agent_locks row either does not exist yet
// (lock has not transferred from source mid-finalize) or no longer
// names this peer as holder (force-reclaim race). The finalize
// handler translates this into a 503 lock_not_self response so the
// source-side deferred-finalize retry loop (which already keys on
// "lock_not_self" substring) picks it up and re-dispatches once
// the lock settles. Without this surface, the retry loop sees a
// generic 500 + "tail apply" error message and gives up on the
// first attempt, stranding target's runtime activation.
var errTailLockNotSelf = errors.New("tail apply: lock_not_self")

// applyFinalizeTailMessage inserts the post-tool-result assistant
// turn shipped from source into target's agent_messages. Source's
// snapshot was taken DURING the kojo-switch-device curl; the
// follow-up text the source's claude generates AFTER the curl
// returns is the agent's own "I'll do X on arrival" commitment.
// Without this apply, target's arrival prompt sees a transcript
// ending at the user instruction + an empty in-flight assistant
// row, and the LLM has no anchor for what work it already
// committed to.
//
// Calls AppendMessage directly rather than SyncAgentFromPeer:
// the peer-sync entrypoint upserts the agent row, persona, memory
// and friends from the payload, so a minimal `Agent{ID}` would
// silently NULL out target's name / persona / memory fields. The
// tail apply must touch ONLY agent_messages.
//
// Fencing: the insert runs under a FencingPredicate keyed on the
// agent_locks row's current (HolderPeer, FencingToken). If the lock
// rotates between the GetAgentLock read and the AppendMessage tx
// (force-reclaim race, source still hosting), the tx aborts with
// ErrFencingMismatch and we surface it so the orchestrator can
// retry. Without fencing, a lock_not_self failure in the surrounding
// finalize step would leave an orphan tail row on a peer that
// doesn't own the agent — silently corrupting target's seq when a
// future switch BACKS to this peer and re-allocates seqs around
// the abandoned row.
//
// Idempotency under retry is enforced by an explicit GetMessage
// pre-check: a second apply of the same id is a no-op so the seq
// doesn't drift forward on every redelivery (without the gate,
// retry #2 reads max=tail.Seq and would write at tail.Seq+1,
// shifting the row each time).
func (s *Server) applyFinalizeTailMessage(ctx context.Context, agentID string, rec *store.MessageRecord) error {
	if rec == nil {
		return nil
	}
	if rec.ID == "" {
		return errors.New("tail message: id required")
	}
	if rec.AgentID != "" && rec.AgentID != agentID {
		return fmt.Errorf("tail message: agent_id mismatch (got %q, want %q)", rec.AgentID, agentID)
	}
	rec.AgentID = agentID

	st := s.agents.Store()

	// Idempotent retry: if id already lives in agent_messages, bail.
	// First-apply's seq is canonical; a second apply must not shift
	// it. ErrNotFound is the expected miss; everything else
	// surfaces as 500 so the orchestrator can retry.
	if existing, err := st.GetMessage(ctx, rec.ID); err == nil && existing != nil {
		return nil
	} else if err != nil && !errors.Is(err, store.ErrNotFound) {
		return fmt.Errorf("tail pre-check: %w", err)
	}

	// Build the fencing predicate from the current lock row. By
	// the time this helper runs, the finalize handler has already
	// accepted ownership and completed the runtime hook, so the lock
	// SHOULD be at us; the checks below catch the post-hook race
	// window:
	//
	//   - ErrNotFound: the agent_locks row vanished between
	//     acceptance and here (for example, shutdown or an explicit
	//     operator delete). Surface
	//     errTailLockNotSelf so the orchestrator retries once the
	//     row is re-acquired.
	//
	//   - Holder mismatch: a different peer reclaimed the lock
	//     in the same window (force-reclaim self-heal landed on
	//     a stranded source row). Same treatment.
	//
	// Both branches return errTailLockNotSelf which the handler
	// translates into 503 lock_not_self.
	var fencing *store.FencingPredicate
	if s.peerID != nil {
		lock, lerr := st.GetAgentLock(ctx, agentID)
		if lerr != nil {
			if errors.Is(lerr, store.ErrNotFound) {
				s.logger.Warn("finalize: agent_locks row absent; tail apply deferred",
					"agent", agentID, "self", s.peerID.DeviceID)
				return errTailLockNotSelf
			}
			return fmt.Errorf("tail apply: get lock: %w", lerr)
		}
		if lock == nil || lock.HolderPeer != s.peerID.DeviceID {
			holder := ""
			if lock != nil {
				holder = lock.HolderPeer
			}
			s.logger.Warn("finalize: lock not at us yet; tail apply deferred (orchestrator will retry)",
				"agent", agentID, "holder", holder, "self", s.peerID.DeviceID)
			return errTailLockNotSelf
		}
		fencing = &store.FencingPredicate{
			AgentID:      agentID,
			Peer:         s.peerID.DeviceID,
			FencingToken: lock.FencingToken,
		}
	}

	// Fresh insert. opts.Seq=0 → AppendMessage allocates max+1
	// inside its own tx. Other fields (timestamps, etag) get
	// recomputed by the store layer; source's wire payload
	// stamped Content / Thinking / ToolUses which are the only
	// authoritative bits we ship.
	//
	// ErrFencingMismatch maps to errTailLockNotSelf — the same
	// race the GetAgentLock check covers, just observed by the
	// store-tx-level fencing gate instead of the pre-read. Both
	// paths feed the source retry.
	if _, err := st.AppendMessage(ctx, rec, store.MessageInsertOptions{
		Fencing: fencing,
	}); err != nil {
		if errors.Is(err, store.ErrFencingMismatch) {
			return errTailLockNotSelf
		}
		return fmt.Errorf("append tail row: %w", err)
	}
	return nil
}

// Drop endpoint for the orchestrator's abort path — clears any
// pending token without activating runtime state. Same auth as
// finalize.
type peerAgentSyncDropRequest struct {
	SourceDeviceID string `json:"source_device_id"`
	AgentID        string `json:"agent_id"`
	OpID           string `json:"op_id"`
}

func (s *Server) handlePeerAgentSyncDrop(w http.ResponseWriter, r *http.Request) {
	p, ok := requirePeerOrOwner(w, r)
	if !ok {
		return
	}
	body, err := io.ReadAll(http.MaxBytesReader(w, r.Body, 4<<10))
	if err != nil {
		writeError(w, http.StatusBadRequest, "bad_request",
			"read body: "+err.Error())
		return
	}
	var req peerAgentSyncDropRequest
	dec := json.NewDecoder(bytes.NewReader(body))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "bad_request",
			"invalid json: "+err.Error())
		return
	}
	if req.AgentID == "" || req.OpID == "" {
		writeError(w, http.StatusBadRequest, "bad_request",
			"agent_id and op_id required")
		return
	}
	if !verifySignerIsSource(p, req.SourceDeviceID) {
		writeError(w, http.StatusForbidden, "forbidden",
			"signer peer device_id does not match source_device_id")
		return
	}
	unlock := s.lockPendingFinalize(pendingSyncKey{AgentID: req.AgentID})
	defer unlock()
	entry, found, err := s.consumePendingAgentSync(r.Context(), req.AgentID, req.OpID)
	if err != nil {
		writeError(w, 500, "internal", err.Error())
		return
	}
	if found && entry.SourceDeviceID != "" && entry.SourceDeviceID != req.SourceDeviceID {
		writeError(w, 403, "forbidden", "drop source differs from phase-1")
		return
	}
	if s.peerID != nil {
		// The snapshot transaction can commit before pending credentials are
		// sealed, and drop can overtake phase-1. Fence both cases durably,
		// independent of whether the pending KV entry exists.
		if err := s.agents.Store().AbortIncomingHandoff(r.Context(), req.AgentID, req.OpID, req.SourceDeviceID); err != nil {
			if errors.Is(err, store.ErrStaleHandoff) {
				writeError(w, 409, "stale_handoff", "cannot drop an accepted handoff or another source's operation")
			} else {
				writeError(w, 500, "internal", err.Error())
			}
			return
		}
	}
	if err := s.dropPendingAgentSync(r.Context(), req.AgentID, req.OpID); err != nil {
		s.logger.Error("peer agent-sync drop: kv delete failed",
			"agent", req.AgentID, "op_id", req.OpID, "err", err)
		writeError(w, http.StatusInternalServerError, "internal",
			"drop kv: "+err.Error())
		return
	}
	writeJSONResponse(w, http.StatusOK, map[string]string{"agent_id": req.AgentID})
}
