package server

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"

	"github.com/loppo-llc/kojo/internal/agent"
	"github.com/loppo-llc/kojo/internal/store"
)

// docs/multi-device-storage.md §3.7 — agent-sync finalize.
//
// The agent-sync push (`POST /api/v1/peers/agent-sync`) lands
// the source's row state on target BEFORE the blob pull and the
// complete commit. If anything between (pull or complete) fails,
// the switch aborts and target's runtime state should NOT
// activate the agent — otherwise target ends up with a valid
// token + lock-guard entry for an agent whose blobs never
// arrived, which would let an unsuspecting Bearer holder write
// to half-migrated state.
//
// The orchestrator dispatches this finalize POST only after a
// successful complete. The handler:
//
//   - consumes the raw $KOJO_AGENT_TOKEN that agent-sync
//     stashed in pendingAgentTokens and adopts it via the local
//     TokenStore (so $KOJO_AGENT_TOKEN injection on the next
//     PTY spawn authenticates),
//   - signals the wired-in onAgentSyncFinalized hook (cmd/kojo
//     hooks AgentLockGuard.AddAgent here).
//
// Route: POST /api/v1/peers/agent-sync/finalize
// Auth: RolePeer (signer.PeerID must equal source_device_id) or
// RoleOwner. Same trust model as agent-sync itself.
//
// Body:
//
//	{ "source_device_id": "...", "agent_id": "..." }
//
// Idempotent: a second finalize for the same agent_id is a no-op
// because the pending token is already consumed.

type peerAgentSyncFinalizeRequest struct {
	SourceDeviceID string `json:"source_device_id"`
	AgentID        string `json:"agent_id"`
	// OpID matches the op_id stamped on the original
	// /peers/agent-sync request. Required for the two-phase
	// protocol; a finalize without a matching pending entry
	// fails 404 not_found rather than activating runtime state
	// blindly.
	OpID string `json:"op_id"`
	// TailMessage carries the assistant Message generated by source's
	// claude AFTER the kojo-switch-device tool_use returned but
	// BEFORE the chat goroutine exited. Optional: the orchestrator
	// includes it only on the self-call defer-finalize path where
	// the source-release guard would otherwise drop this turn.
	//
	// Handler ordering (see handlePeerAgentSyncFinalize):
	//   1. onAgentSyncFinalized hook (AddAgent + lock verify +
	//      ActivateAgentRuntime)
	//   2. UpdateAgentLockAllowedProxy (proxy stamp)
	//   3. applyFinalizeTailMessage — UPSERTs the row by id under
	//      a FencingPredicate keyed on the post-hook lock token,
	//      so a force-reclaim race aborts the apply with
	//      errTailLockNotSelf (caller 503s, source retries).
	//   4. NotifyDeviceSwitchArrival — arrival prompt's transcript
	//      scan now sees the agent's own "I'll do X on arrival"
	//      commitment alongside the user's last instruction.
	//   5. commitPendingAgentSync
	//
	// Nil/empty on non-self-call paths and on self-call paths where
	// the source turn never emitted a done event within the wait
	// budget — the finalize still proceeds; target's arrival just
	// lacks the tail (degraded but functional).
	TailMessage *store.MessageRecord `json:"tail_message,omitempty"`
}

type peerAgentSyncFinalizeResponse struct {
	AgentID string `json:"agent_id"`
}

func (s *Server) handlePeerAgentSyncFinalize(w http.ResponseWriter, r *http.Request) {
	p, ok := requirePeerOrOwner(w, r)
	if !ok {
		return
	}
	// Body cap raised to 16 MiB to admit an optional TailMessage —
	// an assistant turn with long Markdown, multi-tool ToolUses
	// JSON, and tool outputs can easily exceed the legacy 4 KiB.
	// The bound stays well under peerAgentSyncMaxBody so a runaway
	// tail can't exhaust the receiver.
	body, err := io.ReadAll(http.MaxBytesReader(w, r.Body, 16<<20))
	if err != nil {
		writeError(w, http.StatusBadRequest, "bad_request",
			"read body: "+err.Error())
		return
	}
	var req peerAgentSyncFinalizeRequest
	dec := json.NewDecoder(bytes.NewReader(body))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "bad_request",
			"invalid json: "+err.Error())
		return
	}
	if req.SourceDeviceID == "" || req.AgentID == "" || req.OpID == "" {
		writeError(w, http.StatusBadRequest, "bad_request",
			"source_device_id, agent_id, and op_id required")
		return
	}
	if !verifySignerIsSource(p, req.SourceDeviceID) {
		writeError(w, http.StatusForbidden, "forbidden",
			"signer peer device_id does not match source_device_id")
		return
	}

	entry, ok, err := s.consumePendingAgentSync(r.Context(), req.AgentID, req.OpID)
	if err != nil {
		s.logger.Error("peer agent-sync finalize: pending lookup failed",
			"agent", req.AgentID, "op_id", req.OpID, "err", err)
		writeError(w, http.StatusInternalServerError, "internal",
			"pending lookup: "+err.Error())
		return
	}
	if !ok {
		// No matching sync stash. Two cases:
		//   - the orchestrator never sent the agent-sync for
		//     this op_id (forged or wrong-host finalize)
		//   - a prior finalize already committed and removed
		//     the entry (idempotent re-call)
		// Both are surfaced as 404; the orchestrator treats
		// 404 as "nothing to do" so a retry after a successful
		// finalize is a no-op.
		writeError(w, http.StatusNotFound, "not_found",
			"no pending agent-sync for the given (agent_id, op_id); finalize already committed or sync never landed")
		return
	}
	tokenReissued := false
	if s.onAgentSyncFinalized != nil {
		reissued, err := s.onAgentSyncFinalized(r.Context(), req.AgentID, entry.RawToken, req.SourceDeviceID, req.OpID)
		tokenReissued = reissued
		if err != nil {
			// Lock-race surface: cmd/kojo's hook wraps a
			// post-AddAgent holder-mismatch with
			// store.ErrFencingMismatch so the source-side retry
			// loop (which keys on the "lock_not_self" substring)
			// picks it up. Without this translation the retry
			// loop sees a generic 500 and gives up after one
			// attempt — bug observed by codex review when the
			// lock hasn't yet propagated to target's local
			// agent_locks at the moment finalize lands.
			if errors.Is(err, store.ErrFencingMismatch) {
				s.logger.Warn("peer agent-sync finalize: hook lock_not_self; pending retained for retry",
					"agent", req.AgentID, "op_id", req.OpID, "err", err)
				writeError(w, http.StatusServiceUnavailable, "lock_not_self",
					"finalize hook: agent_locks holder mismatch; finalize aborted, orchestrator may retry")
				return
			}
			// Other hook failures (e.g. transient kv write error
			// on AdoptAgentTokenFromPeer) stay as 500 with the
			// pending entry retained. The source-side retry loop
			// only catches lock_not_self; non-matching errors
			// require operator intervention.
			s.logger.Error("peer agent-sync finalize: hook failed; pending entry retained for retry",
				"agent", req.AgentID, "op_id", req.OpID, "err", err)
			writeError(w, http.StatusInternalServerError, "internal",
				"finalize hook: "+err.Error())
			return
		}
	}
	// Single-statement verify + stamp: UpdateAgentLockAllowedProxy
	// only fires when holder_peer == self at the moment of the
	// UPDATE. A concurrent steal between the hook and this call
	// returns ErrFencingMismatch; the pending entry stays so the
	// orchestrator can retry. ErrNotFound means the lock row
	// vanished entirely — same retry semantics.
	//
	// agentHolderAdmitMiddleware gates agents/* on
	// `holder_peer == self AND allowed_proxy_peer == signer`.
	// AcquireAgentLock fresh-row insert lands allowed_proxy_peer
	// = self; we rewrite it to source here so the Hub→target
	// proxy admits. Scoped to a single agent — no
	// peer_registry.trusted flip, so a paired-but-untrusted
	// source can NOT use this as a stepping-stone to
	// sessions/files/git.
	if s.agents != nil && s.agents.Store() != nil && s.peerID != nil {
		err := s.agents.Store().UpdateAgentLockAllowedProxy(
			r.Context(), req.AgentID,
			s.peerID.DeviceID, // expected holder
			req.SourceDeviceID,
		)
		switch {
		case err == nil:
		case errors.Is(err, store.ErrNotFound), errors.Is(err, store.ErrFencingMismatch):
			s.logger.Error("peer agent-sync finalize: holder did not transfer / lock missing; pending retained",
				"agent", req.AgentID, "op_id", req.OpID, "err", err)
			writeError(w, http.StatusServiceUnavailable, "lock_not_self",
				"agent_locks.holder_peer is not the local peer; finalize aborted, orchestrator may retry")
			return
		default:
			s.logger.Error("peer agent-sync finalize: allowed-proxy stamp failed; pending retained",
				"agent", req.AgentID, "source", req.SourceDeviceID, "err", err)
			writeError(w, http.StatusInternalServerError, "internal",
				"allowed-proxy stamp: "+err.Error())
			return
		}
	}
	// Apply the optional Plan A TailMessage AFTER the hook + admit
	// gate have BOTH confirmed the lock is at us. Applying earlier
	// would 503 forever on the first /handoff/finalize attempt —
	// the lock isn't acquired until the hook runs AddAgent, so
	// applyFinalizeTailMessage's holder check would refuse every
	// pre-hook attempt. The fencing predicate on AppendMessage
	// still re-verifies the lock is at us at apply-tx time (covers
	// a force-reclaim race in the gap between
	// UpdateAgentLockAllowedProxy and AppendMessage).
	if req.TailMessage != nil && s.agents != nil && s.agents.Store() != nil {
		if err := s.applyFinalizeTailMessage(r.Context(), req.AgentID, req.TailMessage); err != nil {
			if errors.Is(err, errTailLockNotSelf) {
				s.logger.Warn("peer agent-sync finalize: tail apply lock_not_self after hook; pending retained for retry",
					"agent", req.AgentID, "op_id", req.OpID)
				writeError(w, http.StatusServiceUnavailable, "lock_not_self",
					"tail apply: agent_locks.holder_peer is not the local peer; finalize aborted, orchestrator may retry")
				return
			}
			s.logger.Error("peer agent-sync finalize: tail message apply failed; pending retained",
				"agent", req.AgentID, "op_id", req.OpID, "err", err)
			writeError(w, http.StatusInternalServerError, "internal",
				"tail message apply: "+err.Error())
			return
		}
	}

	// Arrival prompt fire is deliberately AFTER the tail apply.
	// NotifyDeviceSwitchArrival's buildArrivalPrompt reads
	// agent_messages via ListMessages; firing it before the tail
	// landed would build the prompt against an incomplete transcript
	// and quote only the user instruction without the commitment
	// text. Hook-side firing was removed for this reason
	// (cmd/kojo/main.go SetOnAgentSyncFinalized).
	if s.agents != nil {
		sourceName := req.SourceDeviceID
		if req.SourceDeviceID != "" && s.agents.Store() != nil {
			if rec, gerr := s.agents.Store().GetPeer(r.Context(), req.SourceDeviceID); gerr == nil && rec.Name != "" {
				sourceName = rec.Name
			}
		}
		s.agents.NotifyDeviceSwitchArrival(req.AgentID, sourceName, req.OpID, agent.ArrivalNotes{
			TokenReissued:   tokenReissued,
			DegradedFlushes: entry.DegradedFlushes,
			TransferSkips:   entry.TransferSkips,
		})
	}

	// Hook + admit gate + tail + arrival all succeeded — NOW remove
	// the pending entry so a subsequent retry surfaces as the 404
	// idempotent path. A kv delete failure still surfaces as 500:
	// leaving the sealed token in place while telling the
	// orchestrator the op completed would let a later boot consume
	// the same (agent_id, op_id) and replay every hook side
	// effect. All hook steps are idempotent on retry.
	if err := s.commitPendingAgentSync(r.Context(), req.AgentID, req.OpID); err != nil {
		s.logger.Error("peer agent-sync finalize: commit kv delete failed; surface 500 for retry",
			"agent", req.AgentID, "op_id", req.OpID, "err", err)
		writeError(w, http.StatusInternalServerError, "internal",
			"commit kv delete: "+err.Error())
		return
	}
	// Queue-and-forward: the runtime for this agent just activated
	// on this peer (finalize committed). When this peer is the hub,
	// messages queued during the switch can deliver locally right
	// now instead of waiting out the drain's backoff timer; on a
	// non-hub peer the queue table is empty and this is a no-op.
	s.kickHandoffQueueDrain()
	writeJSONResponse(w, http.StatusOK,
		peerAgentSyncFinalizeResponse{AgentID: req.AgentID})
}

// errTailLockNotSelf signals that the tail apply could not proceed
// because target's agent_locks row either does not exist yet
// (lock has not transferred from source mid-finalize) or no longer
// names this peer as holder (force-reclaim race). The finalize
// handler translates this into a 503 lock_not_self response so the
// source-side deferred-finalize retry loop (which already keys on
// "lock_not_self" substring) picks it up and re-dispatches once
// the lock settles. Without this surface, the retry loop sees a
// generic 500 + "tail apply" error message and gives up on the
// first attempt, stranding target's runtime activation.
var errTailLockNotSelf = errors.New("tail apply: lock_not_self")

// applyFinalizeTailMessage inserts the post-tool-result assistant
// turn shipped from source into target's agent_messages. Source's
// snapshot was taken DURING the kojo-switch-device curl; the
// follow-up text the source's claude generates AFTER the curl
// returns is the agent's own "I'll do X on arrival" commitment.
// Without this apply, target's arrival prompt sees a transcript
// ending at the user instruction + an empty in-flight assistant
// row, and the LLM has no anchor for what work it already
// committed to.
//
// Calls AppendMessage directly rather than SyncAgentFromPeer:
// the peer-sync entrypoint upserts the agent row, persona, memory
// and friends from the payload, so a minimal `Agent{ID}` would
// silently NULL out target's name / persona / memory fields. The
// tail apply must touch ONLY agent_messages.
//
// Fencing: the insert runs under a FencingPredicate keyed on the
// agent_locks row's current (HolderPeer, FencingToken). If the lock
// rotates between the GetAgentLock read and the AppendMessage tx
// (force-reclaim race, source still hosting), the tx aborts with
// ErrFencingMismatch and we surface it so the orchestrator can
// retry. Without fencing, a lock_not_self failure in the surrounding
// finalize step would leave an orphan tail row on a peer that
// doesn't own the agent — silently corrupting target's seq when a
// future switch BACKS to this peer and re-allocates seqs around
// the abandoned row.
//
// Idempotency under retry is enforced by an explicit GetMessage
// pre-check: a second apply of the same id is a no-op so the seq
// doesn't drift forward on every redelivery (without the gate,
// retry #2 reads max=tail.Seq and would write at tail.Seq+1,
// shifting the row each time).
func (s *Server) applyFinalizeTailMessage(ctx context.Context, agentID string, rec *store.MessageRecord) error {
	if rec == nil {
		return nil
	}
	if rec.ID == "" {
		return errors.New("tail message: id required")
	}
	if rec.AgentID != "" && rec.AgentID != agentID {
		return fmt.Errorf("tail message: agent_id mismatch (got %q, want %q)", rec.AgentID, agentID)
	}
	rec.AgentID = agentID

	st := s.agents.Store()

	// Idempotent retry: if id already lives in agent_messages, bail.
	// First-apply's seq is canonical; a second apply must not shift
	// it. ErrNotFound is the expected miss; everything else
	// surfaces as 500 so the orchestrator can retry.
	if existing, err := st.GetMessage(ctx, rec.ID); err == nil && existing != nil {
		return nil
	} else if err != nil && !errors.Is(err, store.ErrNotFound) {
		return fmt.Errorf("tail pre-check: %w", err)
	}

	// Build the fencing predicate from the current lock row. By
	// the time this helper runs, the finalize handler has already
	// driven the hook + UpdateAgentLockAllowedProxy so the lock
	// SHOULD be at us; the checks below catch the post-hook race
	// window:
	//
	//   - ErrNotFound: the agent_locks row vanished between
	//     UpdateAgentLockAllowedProxy and here (force-reclaim
	//     wiped it, or a manual operator delete fired). Surface
	//     errTailLockNotSelf so the orchestrator retries once the
	//     row is re-acquired.
	//
	//   - Holder mismatch: a different peer reclaimed the lock
	//     in the same window (force-reclaim self-heal landed on
	//     a stranded source row). Same treatment.
	//
	// Both branches return errTailLockNotSelf which the handler
	// translates into 503 lock_not_self.
	var fencing *store.FencingPredicate
	if s.peerID != nil {
		lock, lerr := st.GetAgentLock(ctx, agentID)
		if lerr != nil {
			if errors.Is(lerr, store.ErrNotFound) {
				s.logger.Warn("finalize: agent_locks row absent; tail apply deferred",
					"agent", agentID, "self", s.peerID.DeviceID)
				return errTailLockNotSelf
			}
			return fmt.Errorf("tail apply: get lock: %w", lerr)
		}
		if lock == nil || lock.HolderPeer != s.peerID.DeviceID {
			holder := ""
			if lock != nil {
				holder = lock.HolderPeer
			}
			s.logger.Warn("finalize: lock not at us yet; tail apply deferred (orchestrator will retry)",
				"agent", agentID, "holder", holder, "self", s.peerID.DeviceID)
			return errTailLockNotSelf
		}
		fencing = &store.FencingPredicate{
			AgentID:      agentID,
			Peer:         s.peerID.DeviceID,
			FencingToken: lock.FencingToken,
		}
	}

	// Fresh insert. opts.Seq=0 → AppendMessage allocates max+1
	// inside its own tx. Other fields (timestamps, etag) get
	// recomputed by the store layer; source's wire payload
	// stamped Content / Thinking / ToolUses which are the only
	// authoritative bits we ship.
	//
	// ErrFencingMismatch maps to errTailLockNotSelf — the same
	// race the GetAgentLock check covers, just observed by the
	// store-tx-level fencing gate instead of the pre-read. Both
	// paths feed the source retry.
	if _, err := st.AppendMessage(ctx, rec, store.MessageInsertOptions{
		Fencing: fencing,
	}); err != nil {
		if errors.Is(err, store.ErrFencingMismatch) {
			return errTailLockNotSelf
		}
		return fmt.Errorf("append tail row: %w", err)
	}
	return nil
}

// Drop endpoint for the orchestrator's abort path — clears any
// pending token without activating runtime state. Same auth as
// finalize.
type peerAgentSyncDropRequest struct {
	SourceDeviceID string `json:"source_device_id"`
	AgentID        string `json:"agent_id"`
	OpID           string `json:"op_id"`
}

func (s *Server) handlePeerAgentSyncDrop(w http.ResponseWriter, r *http.Request) {
	p, ok := requirePeerOrOwner(w, r)
	if !ok {
		return
	}
	body, err := io.ReadAll(http.MaxBytesReader(w, r.Body, 4<<10))
	if err != nil {
		writeError(w, http.StatusBadRequest, "bad_request",
			"read body: "+err.Error())
		return
	}
	var req peerAgentSyncDropRequest
	dec := json.NewDecoder(bytes.NewReader(body))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "bad_request",
			"invalid json: "+err.Error())
		return
	}
	if req.AgentID == "" || req.OpID == "" {
		writeError(w, http.StatusBadRequest, "bad_request",
			"agent_id and op_id required")
		return
	}
	if !verifySignerIsSource(p, req.SourceDeviceID) {
		writeError(w, http.StatusForbidden, "forbidden",
			"signer peer device_id does not match source_device_id")
		return
	}
	if err := s.dropPendingAgentSync(r.Context(), req.AgentID, req.OpID); err != nil {
		s.logger.Error("peer agent-sync drop: kv delete failed",
			"agent", req.AgentID, "op_id", req.OpID, "err", err)
		writeError(w, http.StatusInternalServerError, "internal",
			"drop kv: "+err.Error())
		return
	}
	writeJSONResponse(w, http.StatusOK, map[string]string{"agent_id": req.AgentID})
}
